apiVersion: v1
kind: Service
metadata:
  name: cobrowse-server
  namespace: cobrowse
  labels:
    app.kubernetes.io/name: cobrowse-server
    app.kubernetes.io/part-of: cobrowse
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cobrowse-server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
